version: '3.8'

services:
  smartschool-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./SmartSchool.Api/data:/app/data
    # Configurações para desenvolvimento no Visual Studio
    build:
      target: base
    stdin_open: true
    tty: true


